name: CI/CD Docker Pipeline

# Gatilho: Executa quando há um push na branch main (baseline)
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    name: Construir e Publicar Imagem
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o Docker Buildx (Ferramenta necessária para builds modernos)
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Faz Login no Docker Hub usando os segredos que configuramos
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Constrói a imagem e envia (Push) para o Docker Hub
      - name: Construir e Publicar (Push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Substitua 'seu-usuario-docker' abaixo pelo seu usuário real do DockerHub se preferir hardcode,
          # mas o ideal é usar a secret ou a variável dinâmica.
          # A tag 'latest' indica que é a versão mais recente.
          tags: ${{ secrets.DOCKER_USERNAME }}/minha-biblioteca-api:latest
